-- ============================================================
-- SOURCE QUERY — RPT_CUSTOMER_SUCCESS_METRICS_VW
-- This is the underlying Freshdesk + staffing query that the
-- MCP view RPT_CUSTOMER_SUCCESS_METRICS_VW is based on.
-- Run directly in Snowflake with SYSADMIN / DWH_RO_ROLE.
-- ============================================================

WITH week_dates AS (
    SELECT DISTINCT
        DATEADD(DAY, -1, DATE_TRUNC('WEEK', CONVERT_TIMEZONE('America/Chicago', t.created_at))) AS week_start
    FROM PROD_HIGHLEVEL_DWH.FRESHDESK.TICKET t
    WHERE t.GROUP_ID IN (
        155000000443, 155000000512, 155000000491, 155000000505,
        155000000488, 155000000526, 155000000506, 155000000314,
        48000365697,  155000000308, 155000000528, 155000000529,
        155000000527, 155000000500, 155000000280, 155000000485,
        155000000151
    )
      AND (t.DELETED IS NULL OR t.DELETED = FALSE)
      AND t.created_at >= '2025-04-07'
),

weekly_available_reps AS (
    SELECT
        wd.week_start,
        COUNT(DISTINCT st.email) AS available_reps
    FROM week_dates wd
    JOIN PROD_HIGHLEVEL_DWH.google_sheets.impl_staffing_tracker st
        ON st.role IN ('CSM I', 'CSM II', 'Frontline')
        AND st.available_date <= wd.week_start
        AND (
            st.end_date IS NULL
            OR DATEADD(DAY, -1, DATE_TRUNC('WEEK', CONVERT_TIMEZONE('America/Chicago', st.end_date))) >= wd.week_start
        )
    GROUP BY wd.week_start
),

CSAT_Chat AS (
    SELECT
        INTERACTION_RAW_ID,
        CASE
            WHEN COUNT(CASE WHEN LOWER(actor_type) = 'agent' THEN 1 END) > 0
             AND COUNT(CASE WHEN LOWER(actor_type) = 'user' THEN 1 END) > 0
            THEN 'Yes'
            ELSE 'No'
        END AS csat_sent_flag
    FROM PROD_HIGHLEVEL_DWH.EFFY_FRESHCHAT.CHAT_TRANSCRIPT
    GROUP BY INTERACTION_RAW_ID
),

converted_ticket_time AS (
    SELECT ID, created_at, CONVERT_TIMEZONE('America/Chicago', created_at) AS CREATED_AT_NEW
    FROM PROD_HIGHLEVEL_DWH.FRESHDESK.TICKET
),

booked_csat AS (
    SELECT
        TICKET_ID_,
        ROUND(
            (
                COALESCE(CASE
                    WHEN UPPER(Q_1_S_1_HOW_WOULD_YOU_RATE_THE_CLARITY_AND_SUPPORT_PROVIDED_BY_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%VERY CLEAR%' THEN 5
                    WHEN UPPER(Q_1_S_1_HOW_WOULD_YOU_RATE_THE_CLARITY_AND_SUPPORT_PROVIDED_BY_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%CLEAR AND GENERALLY%' THEN 4
                    WHEN UPPER(Q_1_S_1_HOW_WOULD_YOU_RATE_THE_CLARITY_AND_SUPPORT_PROVIDED_BY_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(Q_1_S_1_HOW_WOULD_YOU_RATE_THE_CLARITY_AND_SUPPORT_PROVIDED_BY_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%SOMEWHAT UNCLEAR%' THEN 2
                    WHEN UPPER(Q_1_S_1_HOW_WOULD_YOU_RATE_THE_CLARITY_AND_SUPPORT_PROVIDED_BY_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%VERY UNCLEAR%' THEN 1
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(Q_4_S_1_HOW_CONFIDENT_DO_YOU_FEEL_USING_HIGH_LEVEL_TO_ACHIEVE_YOUR_GOALS_) LIKE '%VERY CONFIDENT%' THEN 5
                    WHEN UPPER(Q_4_S_1_HOW_CONFIDENT_DO_YOU_FEEL_USING_HIGH_LEVEL_TO_ACHIEVE_YOUR_GOALS_) LIKE '%MODERATELY CONFIDENT%' THEN 3
                    WHEN UPPER(Q_4_S_1_HOW_CONFIDENT_DO_YOU_FEEL_USING_HIGH_LEVEL_TO_ACHIEVE_YOUR_GOALS_) LIKE '%SLIGHTLY CONFIDENT%' THEN 2
                    WHEN UPPER(Q_4_S_1_HOW_CONFIDENT_DO_YOU_FEEL_USING_HIGH_LEVEL_TO_ACHIEVE_YOUR_GOALS_) LIKE '%NOT AT ALL CONFIDENT%' THEN 1
                    WHEN UPPER(Q_4_S_1_HOW_CONFIDENT_DO_YOU_FEEL_USING_HIGH_LEVEL_TO_ACHIEVE_YOUR_GOALS_) LIKE '%CONFIDENT%' THEN 4
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(Q_1_S_2_HOW_EASY_HAS_IT_BEEN_TO_IMPLEMENT_WHAT_YOU_VE_LEARNED_SO_FAR_) LIKE '%VERY EASY%' THEN 5
                    WHEN UPPER(Q_1_S_2_HOW_EASY_HAS_IT_BEEN_TO_IMPLEMENT_WHAT_YOU_VE_LEARNED_SO_FAR_) LIKE '%GENERALLY EASY%' THEN 4
                    WHEN UPPER(Q_1_S_2_HOW_EASY_HAS_IT_BEEN_TO_IMPLEMENT_WHAT_YOU_VE_LEARNED_SO_FAR_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(Q_1_S_2_HOW_EASY_HAS_IT_BEEN_TO_IMPLEMENT_WHAT_YOU_VE_LEARNED_SO_FAR_) LIKE '%SOMEWHAT DIFFICULT%' THEN 2
                    WHEN UPPER(Q_1_S_2_HOW_EASY_HAS_IT_BEEN_TO_IMPLEMENT_WHAT_YOU_VE_LEARNED_SO_FAR_) LIKE '%VERY DIFFICULT%' THEN 1
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(Q_3_S_2_HOW_SATISFIED_ARE_YOU_WITH_THE_SUPPORT_AND_GUIDANCE_FROM_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%VERY SATISFIED%' THEN 5
                    WHEN UPPER(Q_3_S_2_HOW_SATISFIED_ARE_YOU_WITH_THE_SUPPORT_AND_GUIDANCE_FROM_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%SOMEWHAT SATISFIED%' THEN 4
                    WHEN UPPER(Q_3_S_2_HOW_SATISFIED_ARE_YOU_WITH_THE_SUPPORT_AND_GUIDANCE_FROM_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(Q_3_S_2_HOW_SATISFIED_ARE_YOU_WITH_THE_SUPPORT_AND_GUIDANCE_FROM_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%SOMEWHAT DISSATISFIED%' THEN 2
                    WHEN UPPER(Q_3_S_2_HOW_SATISFIED_ARE_YOU_WITH_THE_SUPPORT_AND_GUIDANCE_FROM_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%VERY DISSATISFIED%' THEN 1
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(Q_1_S_3_HOW_EFFECTIVE_WAS_YOUR_CUSTOMER_SUCCESS_MANAGER_IN_ADDRESSING_YOUR_QUESTIONS_AND_CONCERNS_) LIKE '%VERY EFFECTIVE%' THEN 5
                    WHEN UPPER(Q_1_S_3_HOW_EFFECTIVE_WAS_YOUR_CUSTOMER_SUCCESS_MANAGER_IN_ADDRESSING_YOUR_QUESTIONS_AND_CONCERNS_) LIKE '%SOMEWHAT EFFECTIVE%' THEN 4
                    WHEN UPPER(Q_1_S_3_HOW_EFFECTIVE_WAS_YOUR_CUSTOMER_SUCCESS_MANAGER_IN_ADDRESSING_YOUR_QUESTIONS_AND_CONCERNS_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(Q_1_S_3_HOW_EFFECTIVE_WAS_YOUR_CUSTOMER_SUCCESS_MANAGER_IN_ADDRESSING_YOUR_QUESTIONS_AND_CONCERNS_) LIKE '%SOMEWHAT INEFFECTIVE%' THEN 2
                    WHEN UPPER(Q_1_S_3_HOW_EFFECTIVE_WAS_YOUR_CUSTOMER_SUCCESS_MANAGER_IN_ADDRESSING_YOUR_QUESTIONS_AND_CONCERNS_) LIKE '%VERY INEFFECTIVE%' THEN 1
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(Q_2_S_3_HOW_WELL_IS_HIGH_LEVEL_HELPING_YOU_ACHIEVE_YOUR_INTENDED_GOALS_) LIKE '%VERY CLEAR%' THEN 5
                    WHEN UPPER(Q_2_S_3_HOW_WELL_IS_HIGH_LEVEL_HELPING_YOU_ACHIEVE_YOUR_INTENDED_GOALS_) LIKE '%CLEAR AND GENERALLY%' THEN 4
                    WHEN UPPER(Q_2_S_3_HOW_WELL_IS_HIGH_LEVEL_HELPING_YOU_ACHIEVE_YOUR_INTENDED_GOALS_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(Q_2_S_3_HOW_WELL_IS_HIGH_LEVEL_HELPING_YOU_ACHIEVE_YOUR_INTENDED_GOALS_) LIKE '%SOMEWHAT UNCLEAR%' THEN 2
                    WHEN UPPER(Q_2_S_3_HOW_WELL_IS_HIGH_LEVEL_HELPING_YOU_ACHIEVE_YOUR_INTENDED_GOALS_) LIKE '%VERY UNCLEAR%' THEN 1
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(Q_1_S_4_HOW_LIKELY_ARE_YOU_TO_RECOMMEND_HIGH_LEVEL_TO_OTHERS_) LIKE '%VERY LIKELY%' THEN 5
                    WHEN UPPER(Q_1_S_4_HOW_LIKELY_ARE_YOU_TO_RECOMMEND_HIGH_LEVEL_TO_OTHERS_) LIKE '%SOMEWHAT LIKELY%' THEN 4
                    WHEN UPPER(Q_1_S_4_HOW_LIKELY_ARE_YOU_TO_RECOMMEND_HIGH_LEVEL_TO_OTHERS_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(Q_1_S_4_HOW_LIKELY_ARE_YOU_TO_RECOMMEND_HIGH_LEVEL_TO_OTHERS_) LIKE '%SOMEWHAT UNLIKELY%' THEN 2
                    WHEN UPPER(Q_1_S_4_HOW_LIKELY_ARE_YOU_TO_RECOMMEND_HIGH_LEVEL_TO_OTHERS_) LIKE '%VERY UNLIKELY%' THEN 1
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(Q_2_S_4_HOW_SATISFIED_ARE_YOU_WITH_YOUR_OVERALL_EXPERIENCE_WITH_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%VERY SATISFIED%' THEN 5
                    WHEN UPPER(Q_2_S_4_HOW_SATISFIED_ARE_YOU_WITH_YOUR_OVERALL_EXPERIENCE_WITH_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%SOMEWHAT SATISFIED%' THEN 4
                    WHEN UPPER(Q_2_S_4_HOW_SATISFIED_ARE_YOU_WITH_YOUR_OVERALL_EXPERIENCE_WITH_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(Q_2_S_4_HOW_SATISFIED_ARE_YOU_WITH_YOUR_OVERALL_EXPERIENCE_WITH_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%SOMEWHAT DISSATISFIED%' THEN 2
                    WHEN UPPER(Q_2_S_4_HOW_SATISFIED_ARE_YOU_WITH_YOUR_OVERALL_EXPERIENCE_WITH_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE '%VERY DISSATISFIED%' THEN 1
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(PAC_Q_1_HOW_SATISFIED_ARE_YOU_WITH_THE_CALL_) LIKE '%VERY SAT%' THEN 5
                    WHEN UPPER(PAC_Q_1_HOW_SATISFIED_ARE_YOU_WITH_THE_CALL_) LIKE '%VERY DISSATISFIED%' THEN 1
                    WHEN UPPER(PAC_Q_1_HOW_SATISFIED_ARE_YOU_WITH_THE_CALL_) LIKE '%DISSATISFIED%' THEN 2
                    WHEN UPPER(PAC_Q_1_HOW_SATISFIED_ARE_YOU_WITH_THE_CALL_) LIKE '%NEUTRAL%' THEN 3
                    WHEN UPPER(PAC_Q_1_HOW_SATISFIED_ARE_YOU_WITH_THE_CALL_) LIKE '%SATISFIED%' THEN 4
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(PAC_Q_2_HOW_VALUABLE_WAS_THIS_SESSION_IN_HELPING_YOU_ADOPT_AND_USE_THE_FEATURE_) LIKE '%EXTREMELY VALUABLE%' THEN 5
                    WHEN UPPER(PAC_Q_2_HOW_VALUABLE_WAS_THIS_SESSION_IN_HELPING_YOU_ADOPT_AND_USE_THE_FEATURE_) LIKE '%VERY VALUABLE%' THEN 5
                    WHEN UPPER(PAC_Q_2_HOW_VALUABLE_WAS_THIS_SESSION_IN_HELPING_YOU_ADOPT_AND_USE_THE_FEATURE_) LIKE '%MODERATELY VALUABLE%' THEN 4
                    WHEN UPPER(PAC_Q_2_HOW_VALUABLE_WAS_THIS_SESSION_IN_HELPING_YOU_ADOPT_AND_USE_THE_FEATURE_) LIKE '%SLIGHT VALUABLE%' THEN 3
                    WHEN UPPER(PAC_Q_2_HOW_VALUABLE_WAS_THIS_SESSION_IN_HELPING_YOU_ADOPT_AND_USE_THE_FEATURE_) LIKE '%NOT VALUABLE%' THEN 1
                    WHEN UPPER(PAC_Q_2_HOW_VALUABLE_WAS_THIS_SESSION_IN_HELPING_YOU_ADOPT_AND_USE_THE_FEATURE_) LIKE '%VALUABLE%' THEN 4
                END, 0)
                + COALESCE(CASE
                    WHEN UPPER(PAC_Q_3_AFTER_THE_CALL_HOW_CONFIDENT_DO_YOU_FEEL_IN_USING_THE_PRODUCT_FEATURES_WE_COVERED_) LIKE '%VERY CONFIDENT%' THEN 5
                    WHEN UPPER(PAC_Q_3_AFTER_THE_CALL_HOW_CONFIDENT_DO_YOU_FEEL_IN_USING_THE_PRODUCT_FEATURES_WE_COVERED_) LIKE '%MODERATELY CONFIDENT%' THEN 3
                    WHEN UPPER(PAC_Q_3_AFTER_THE_CALL_HOW_CONFIDENT_DO_YOU_FEEL_IN_USING_THE_PRODUCT_FEATURES_WE_COVERED_) LIKE '%SLIGHTLY CONFIDENT%' THEN 2
                    WHEN UPPER(PAC_Q_3_AFTER_THE_CALL_HOW_CONFIDENT_DO_YOU_FEEL_IN_USING_THE_PRODUCT_FEATURES_WE_COVERED_) LIKE '%NOT AT ALL CONFIDENT%' THEN 1
                    WHEN UPPER(PAC_Q_3_AFTER_THE_CALL_HOW_CONFIDENT_DO_YOU_FEEL_IN_USING_THE_PRODUCT_FEATURES_WE_COVERED_) LIKE '%CONFIDENT%' THEN 4
                END, 0)
            )
            /
            NULLIF(
                IFF(UPPER(Q_1_S_1_HOW_WOULD_YOU_RATE_THE_CLARITY_AND_SUPPORT_PROVIDED_BY_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE ANY ('%CLEAR%','%NEUTRAL%','%UNCLEAR%'), 1, 0)
              + IFF(UPPER(Q_4_S_1_HOW_CONFIDENT_DO_YOU_FEEL_USING_HIGH_LEVEL_TO_ACHIEVE_YOUR_GOALS_) LIKE ANY ('%CONFIDENT%','%NOT AT ALL%'), 1, 0)
              + IFF(UPPER(Q_1_S_2_HOW_EASY_HAS_IT_BEEN_TO_IMPLEMENT_WHAT_YOU_VE_LEARNED_SO_FAR_) LIKE ANY ('%EASY%','%NEUTRAL%','%DIFFICULT%'), 1, 0)
              + IFF(UPPER(Q_3_S_2_HOW_SATISFIED_ARE_YOU_WITH_THE_SUPPORT_AND_GUIDANCE_FROM_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE ANY ('%SATISFIED%','%NEUTRAL%','%DISSATISFIED%'), 1, 0)
              + IFF(UPPER(Q_1_S_3_HOW_EFFECTIVE_WAS_YOUR_CUSTOMER_SUCCESS_MANAGER_IN_ADDRESSING_YOUR_QUESTIONS_AND_CONCERNS_) LIKE ANY ('%EFFECTIVE%','%NEUTRAL%','%INEFFECTIVE%'), 1, 0)
              + IFF(UPPER(Q_2_S_3_HOW_WELL_IS_HIGH_LEVEL_HELPING_YOU_ACHIEVE_YOUR_INTENDED_GOALS_) LIKE ANY ('%CLEAR%','%NEUTRAL%','%UNCLEAR%'), 1, 0)
              + IFF(UPPER(Q_1_S_4_HOW_LIKELY_ARE_YOU_TO_RECOMMEND_HIGH_LEVEL_TO_OTHERS_) LIKE ANY ('%LIKELY%','%NEUTRAL%','%UNLIKELY%'), 1, 0)
              + IFF(UPPER(Q_2_S_4_HOW_SATISFIED_ARE_YOU_WITH_YOUR_OVERALL_EXPERIENCE_WITH_YOUR_CUSTOMER_SUCCESS_MANAGER_) LIKE ANY ('%SATISFIED%','%NEUTRAL%','%DISSATISFIED%'), 1, 0)
              + IFF(UPPER(PAC_Q_1_HOW_SATISFIED_ARE_YOU_WITH_THE_CALL_) LIKE ANY ('%SAT%','%NEUTRAL%','%DISSATISFIED%'), 1, 0)
              + IFF(UPPER(PAC_Q_2_HOW_VALUABLE_WAS_THIS_SESSION_IN_HELPING_YOU_ADOPT_AND_USE_THE_FEATURE_) LIKE ANY ('%VALUABLE%'), 1, 0)
              + IFF(UPPER(PAC_Q_3_AFTER_THE_CALL_HOW_CONFIDENT_DO_YOU_FEEL_IN_USING_THE_PRODUCT_FEATURES_WE_COVERED_) LIKE ANY ('%CONFIDENT%','%NOT AT ALL%'), 1, 0)
            , 0)
        , 2) AS booked_CSAT
    FROM PROD_HIGHLEVEL_DWH.google_sheets.csm_csats_all_call_type
)

SELECT
    t.ID,
    t.created_at,
    TO_CHAR(CONVERT_TIMEZONE('America/Chicago', ctt.CREATED_AT_NEW), 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT_NEW,
    DATEADD(DAY, -1, DATE_TRUNC('WEEK', CONVERT_TIMEZONE('America/Chicago', t.created_at))) AS WEEK_CREATED_AT_NEW,
    EXTRACT(HOUR FROM CONVERT_TIMEZONE('UTC', 'America/Chicago', TO_TIMESTAMP_TZ(t.created_at)::timestamp_ntz)) AS hour_of_day,

    t.GROUP_ID,
    t.COMPANY_ID AS FD_COMPANY_ID,
    t.PRIORITY,
    t.FR_ESCALATED,
    t.SUBJECT,
    t.TYPE,
    t.DELETED,
    t.IS_ESCALATED,
    t.DESCRIPTION_TEXT,
    t.CUSTOM_CF_RELATIONSHIP_NUMBER,
    t.CUSTOM_CF_HELP_DOC_PROVIDED_LEVEL_1_HELP_DOC_DEFLECTION,
    t.CUSTOM_CF_SEVERITY_LEVEL,
    t.CUSTOM_CF_DONOTTOUCHPRODUCT,
    t.CUSTOM_CF_TEXT_COMPANY_PLAN_LEVEL,
    t.CUSTOM_CF_AGENCY_CREATION_DATE,
    t.CUSTOM_CF_FC_INTERACTION_ID,
    t.CUSTOM_CF_FC_AVERAGE_WAIT_TIME_MINS,
    t.CUSTOM_CF_CONVERSATION_ID,
    t.CUSTOM_CF_FC_CHAT_AGENT,
    t.CUSTOM_CF_ESCALATE_SUCCESS_TICKET_TO_SUPPORT,
    t.CUSTOM_CF_BOT_VERSION,
    t.CUSTOM_CF_PRIORITY,
    t.CUSTOM_CF_SUCCESS_SLA_BREACHED,
    t.CUSTOM_CF_ORIGINAL_TICKET_TYPE,
    t.CUSTOM_CF_TWILIO_TICKET_NUMBER,
    t.CUSTOM_CF_FC_ESCALATED_TO_SENIOR,
    t.CUSTOM_CF_PREVIOUS_AGENT,
    t.CUSTOM_CF_S_CALL_TYPE,
    t.CUSTOM_CF_S_NOTES_FROM_CALL,
    t.CUSTOM_CF_INTERNAL_TEAM_SELECTED,
    t.CUSTOM_CF_BAS_CALL_FEEDBACK,
    t.CUSTOM_CF_CONSENT_TO_RECORD,
    t.CUSTOM_CF_LOOM_RECORDING_URL,
    t.CUSTOM_CF_TICKET_CORRECTLY_ESCALATED,
    t.CUSTOM_CF_SPANISH_SUPPORT,
    t.CUSTOM_CF_REASSIGN_AGENT,
    t.CUSTOM_CF_FC_RESOLUTION_TIMESTAMP,
    t.CUSTOM_CF_FC_CREATION_TIMESTAMP,
    t.CUSTOM_CF_DSAT_CALL_RESOLUTION,
    t.CUSTOM_CF_LEFT_ZOOM_EARLY,
    t.CUSTOM_CF_S_CALL_REASON,
    t.CUSTOM_CF_CALL_ABANDONED,
    t.CUSTOM_CF_ESCALATE_TO_SENIOR_ADVISOR,
    t.CUSTOM_CF_IMPLEMENTATION_2_COMPLETED,
    t.CUSTOM_CF_IMPLEMENTATION_1_COMPLETED,
    t.CUSTOM_CF_WAS_A_PROMOTION_GIVEN,
    t.CUSTOM_CF_DID_SOMEONE_ASSIST_ON_YOUR_CALL,
    t.CUSTOM_CF_S_CALL_SOURCE,
    t.CUSTOM_CF_BAS_CALL_DATE,
    t.CUSTOM_CF_BAS_CALL_1_REP,
    t.CUSTOM_CF_BAS_CALL_2_REP,
    t.CUSTOM_CF_BAS_CALL_REP,
    t.CUSTOM_CF_AFFILIATE_WHO_SIGNED_UP_CUSTOMER,
    t.CUSTOM_CF_FIRST_IMPLEMENTATION_CALL_DATE,
    t.CUSTOM_CF_FIRST_IMPLEMENTATION_CALL_REP,
    t.CUSTOM_CF_SECOND_IMPLEMENTATION_CALL_REP,
    t.CUSTOM_CF_CURRENT_NUMBER_OF_SUBACCOUNTS,
    t.CUSTOM_CF_IMPLEMENTATION_SETUP_CHECKLIST,
    t.CUSTOM_CF_NOTES_FROM_CS_TEAM,
    t.CUSTOM_CF_ADDITIONAL_CALL_NEEDED,
    t.CUSTOM_CF_BAS_CALL_2_DATE,
    t.CUSTOM_CF_SECOND_IMPLEMENTATION_CALL_DATE,
    t.CUSTOM_CF_S_DID_NOT_ARRIVE,
    t.CUSTOM_CF_EXTRA_PERSON_ON_THE_CALL,
    t.CUSTOM_CF_STRIPE_CUSTOMER_ID,
    t.CUSTOM_CF_BAS_PURCHASE,
    t.CUSTOM_CF_S_CALL_SESSION,
    t.CUSTOM_CF_SPLIT_TICKET,
    t.CUSTOM_CF_FRESHCHAT_AGENT,
    t.CUSTOM_CF_S_CALL_STAGE,
    t.CUSTOM_CF_S_CONCIERGE_ABANDON_TYPE,
    t.CUSTOM_CF_S_FRESHCHAT_GROUP_ASSIGNED,
    t.CUSTOM_CF_S_CUSTOMER_CARE_AGENT,
    t.CUSTOM_CF_S_MOB,
    t.custom_cf_senior_assigned,
    t.custom_cf_call_STATUS,
    t.status AS ticket_status,
    t.stats_resolved_at,
    t.source AS ticket_source,
    t.custom_cf_product_group_label,
    t.CUSTOM_CF_SUPPORT_POD AS product_label,

    comp.ID AS COMPANY_ID,
    comp.CUSTOM_RELATIONSHIP_NUMBER,
    comp.CUSTOM_STRIPE_CUSTOMER_ID,
    comp.CUSTOM_EMAIL,
    comp.CUSTOM_COUNTRY,
    comp.CUSTOM_AFFILIATE_REFERRAL_ID,
    comp.CUSTOM_PHONE,
    comp.CUSTOM_COMPANY_PLAN_LEVEL,

    fa.CONTACT_JOB_TITLE AS freshdesk_agent_title,
    fa.CONTACT_EMAIL AS freshdesk_agent_email,
    fa.CONTACT_NAME AS freshdesk_agent_name,

    a.id AS AGENT_ID,

    st.END_SHIFT,
    LOWER(st.EMAIL),
    st.F,
    st.FULL_NAME,
    st.TEAM_MEETING_GROUP,
    st.MANAGER,
    st.DAYS_IN_TRAINING,
    st.M,
    st.NAME,
    st.START_DATE,
    st.S,
    st.T,
    st.START_SHIFT,
    st.W,
    st.CERTIFIED_ADMIN,
    st.NSD,
    st.STATUS,
    st.SHIFT,
    st.SHIFT_DAY,
    st.EOR,
    st.PROMOTION_,
    st.AVAILABLE_DATE,
    st.DAYS_HERE,
    st.ROLE,
    st.SCHEDULE_REVIEWED,
    st.END_DATE,
    st.PROF_DEV,
    st.SHIFT_GROUP,
    st.DAYS,
    st.FIRST_DAY_OF_CURRENT_ROLE,
    st.E_,
    st.SHIFT_CHANGE,

    cst.csat_sent_flag,

    nt.CUSTOMER_METADATA_RELATIONSHIP_NUMBER AS Trial_Relationship_number,
    nt.IMPLEMENTATION_ENGAGEMENT,
    nt.TRIAL_EXPERIENCE,
    nt.CAMPAIGN_NAME,
    nt.AFFILIATE_MANAGER,
    nt.CM_CUSTOMER_CUSTOMER_SINCE,
    nt.COMPUTED_TRIAL_SCORE AS trial_score,

    wr.available_reps AS total_available_reps_this_week,

    bc.booked_CSAT

FROM PROD_HIGHLEVEL_DWH.FRESHDESK.TICKET t
LEFT JOIN converted_ticket_time ctt
    ON t.id = ctt.id
LEFT JOIN CSAT_Chat cst
    ON t.CUSTOM_CF_FC_INTERACTION_ID = cst.INTERACTION_RAW_ID
LEFT JOIN PROD_HIGHLEVEL_DWH.FRESHDESK.agent fa
    ON t.responder_id = fa.id
LEFT JOIN PROD_HIGHLEVEL_DWH.EFFY_FRESHCHAT.AGENTS a
    ON a.EMAIL = fa.CONTACT_EMAIL
LEFT JOIN PROD_HIGHLEVEL_DWH.FRESHDESK.COMPANY comp
    ON t.CUSTOM_CF_STRIPE_CUSTOMER_ID = comp.CUSTOM_STRIPE_CUSTOMER_ID
LEFT JOIN PROD_HIGHLEVEL_DWH.google_sheets.impl_staffing_tracker st
    ON fa.CONTACT_EMAIL = LOWER(st.EMAIL)
LEFT JOIN PROD_HIGHLEVEL_DWH.MOZART.NEW_TRIALS nt
    ON TRY_CAST(NULLIF(t.CUSTOM_CF_RELATIONSHIP_NUMBER, '') AS NUMBER) = TRY_CAST(NULLIF(nt.CUSTOMER_METADATA_RELATIONSHIP_NUMBER, '') AS NUMBER)
LEFT JOIN weekly_available_reps wr
    ON wr.week_start = DATEADD(DAY, -1, DATE_TRUNC('WEEK', CONVERT_TIMEZONE('America/Chicago', t.created_at)))
LEFT JOIN booked_csat bc
    ON t.ID = TRY_CAST(NULLIF(bc.TICKET_ID_, '') AS NUMBER)

WHERE
    t.GROUP_ID IN (
        155000000443, 155000000512, 155000000491, 155000000505,
        155000000488, 155000000526, 155000000506, 155000000314,
        48000365697,  155000000308, 155000000528, 155000000529,
        155000000527, 155000000500, 155000000280, 155000000485,
        155000000151
    )
    AND TO_CHAR(CONVERT_TIMEZONE('America/Chicago', t.created_at), 'YYYY-MM-DD HH24:MI:SS') > '2025-09-01'
    AND (t.DELETED IS NULL OR t.DELETED = FALSE)
